#%RAML 1.0 Library
usage: Open Banking definitions relating to Account information services.

types:
  FundsAvailableResult:
    type: object
    properties:
      FundsAvailableDataTime: datetime
      FundsAvailable: boolean
